#!/usr/bin/python

import subprocess
import sys

if __name__=="__main__":
    network_list_command = "neutron net-list|tail -n+4|awk -F '|' '{print $2}'| grep -v -e '^$'"
    network_list = subprocess.Popen(network_list_command, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)         
    network_list, error = network_list.communicate()
    network_list = network_list.strip()
    network_count, dnsmasq_count = 0,0
    failed_network = []
    for line in network_list.splitlines():
        if line is not None:
            network_count += 1
            command = "ps -eaf|grep dnsmasq|grep %s" % line
            output = subprocess.Popen(command, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)         
            output, error = output.communicate()
            if output is not None:
                dnsmasq_count += 1
            else:
                command = "neutron net-list|grep %s|awk -F '|' '{print $3}'" % line
                network_name = subprocess.Popen(command, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
                network_name, error = output.communicate()
                failed_network.append(network_name)
    print "Network count: %s  Dnsmasq count: %s" % (network_count, dnsmasq_count)
    if network_count == dnsmasq_count:
        sys.exit(0)
    print "Failed networks-"
    for network in failed_network:
        print network
    sys.exit(2)
