#!/bin/bash

#
# Plugin to check the status of a service, using
# 'service <service_name> status' command
#


SERVICE=$1
STATE=$(service $SERVICE status | grep -w 'start\|is running' | wc -l)

if [ "$STATE" == "1" ]; then
        echo "$SERVICE is running"
        exit 0
fi

STATE=$(service $SERVICE status | grep -w 'stop\|waiting\|not running' | wc -l)

if [ "$STATE" == "1" ]; then
        echo "$SERVICE is down"
        exit 0
fi

echo "Service is in unknown state or is unrecognized"
exit 2
