#!/bin/bash

#The following plugin deletes all instances(VMs) belonging to a user.
#Note: Need to 'source admin-openrc.sh' file before running the script

USERNAME=$1

mapfile -t PROJECT_LIST < <(openstack project list|egrep -v "+----|Name"|awk -F '|' '{print $2}')
PROJECT_ID=()

for pid in "${PROJECT_LIST[@]}"; do
	USER_IN_PROJECT=$(openstack user list --project $pid|grep -w $USERNAME)
	if [ ! -z "$USER_IN_PROJECT" ]; then
		PROJECT_ID+=($pid)
	fi
done

for pid in "${PROJECT_ID[@]}"; do
	c=0
	mapfile -t VM_LIST < <(nova list --tenant $pid|egrep -v "+----|ID"|awk -F '|' '{print $2}')
	for vid in "${VM_LIST[@]}"; do
		NAME=$(nova show $vid|grep -w user_id|awk -F '|' '{print $3}'|xargs)
		if [ "$USERNAME" != "$NAME" ]; then
			continue
		fi
		DEL=$(nova delete $vid)
		((c++))
	done
	if [ $c == 0 ]; then
		echo "No existing instances for user $USERNAME in project $pid"
	else
		echo "$c instances for user $USERNAME in project $pid have been deleted"	
	fi
done
